
name: Build S

on:
  push:
    branches:
      - main
      - lineage-20
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Prepare the environment
      run: |
        sudo apt update && sudo apt upgrade -y
        DEBIAN_FRONTEND=noninteractive sudo apt install -yq \
            linux-modules-extra-$(uname -r) \
            gperf gcc-multilib gcc-10-multilib g++-multilib g++-10-multilib \
            libc6-dev lib32ncurses-dev x11proto-core-dev libx11-dev tree lib32z-dev libgl1-mesa-dev libxml2-utils \
            xsltproc bc ccache lib32readline-dev lib32z1-dev liblz4-tool libncurses-dev libsdl1.2-dev \
            build-essential libgtk-3-dev libglu1-mesa-dev freeglut3-dev git libxml2 lzop pngcrush schedtool squashfs-tools \
            imagemagick libbz2-dev lzma ncftp qemu-user-static libstdc++-10-dev libncurses6 python3 tar

            - name: Install OpenJDK
        uses: actions/setup-java@v4
       with:
        distribution: 'zulu'
        java-version: '11'

        - name: Install repo
      run: |
        mkdir ~/bin
        curl https://storage.googleapis.com/git-repo-downloads/repo > ~/bin/repo
        chmod a+x ~/bin/repo
        sudo ln -sf ~/bin/repo /usr/bin/repo

         - name: Initialize repo
      run: |
        mkdir workspace
        cd workspace
        echo "workspace-folder=$(pwd)" >> $GITHUB_OUTPUT
        git config --global user.name "Nico170420"
        git config --global user.email "b170420nc@gmail.com"
      id: pwd
      
      - name: Initialize and sync LineageOS source
        shell: bash
        run: |
          repo init -u https://github.com/LineageOS/android.git -b lineage-20
          repo sync -c -j$(nproc) --force-sync --no-clone-bundle --no-tags

      - name: Clone device, kernel, vendor trees
        shell: bash
        run: |
          git clone https://github.com/your-username/device_samsung_a10s.git device/samsung/a10s
          git clone https://github.com/your-username/kernel_samsung_a10s.git kernel/samsung/a10s
          git clone https://github.com/your-username/vendor_samsung_a10s.git vendor/samsung/a10s

      - name: Setup environment and lunch device
        shell: bash
        run: |
          source build/envsetup.sh
          breakfast a10s userdebug

      - name: Build ROM
        shell: bash
        run: |
          mka bacon

      - name: Prepare output for release
        shell: bash
        run: |
          mkdir -p output
          cp out/target/product/a10s/lineage_a10s.zip output/

      - name: Create GitHub Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: "lineage-a10s-${{ github.run_number }}"
          release_name: "LineageOS A10s Build #${{ github.run_number }}"
          draft: false
          prerelease: false

      - name: Upload ROM ZIP to Release
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: output/lineage_a10s.zip
          asset_name: lineage_a10s_build_${{ github.run_number }}.zip
          asset_content_type: application/zip
